CREATE DATABASE IF NOT EXISTS chimsiq_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE chimsiq_db;

CREATE TABLE IF NOT EXISTS STORE (
    StoreID INT AUTO_INCREMENT PRIMARY KEY,
    StoreName VARCHAR(255) NOT NULL UNIQUE,
    AdminUserID INT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_store_name (StoreName)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USER (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(150) NOT NULL,
    Email VARCHAR(255) UNIQUE NULL,
    StaffID VARCHAR(50) UNIQUE NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role ENUM('superadmin','admin','staff') NOT NULL DEFAULT 'staff',
    StoreID INT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,
    INDEX idx_user_store (StoreID),
    INDEX idx_user_role (Role)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SUPPLIER (
    SupplierID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    SupplierName VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(255),
    Address VARCHAR(255),

    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,
    INDEX idx_supplier_store (StoreID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORY (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    CategoryName VARCHAR(255) NOT NULL,
    Description VARCHAR(255),
    Status ENUM('active','inactive') DEFAULT 'active',

    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,
    INDEX idx_cat_store (StoreID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCT (
    ProductID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    CategoryID INT NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    Description VARCHAR(500),
    Price DECIMAL(10,2) NOT NULL,
    Brand VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT check_price CHECK (Price > 0),

    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,
    FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE RESTRICT,

    INDEX idx_product_store (StoreID),
    INDEX idx_product_name (ProductName)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCT_SUPPLIER (
    ProductID INT NOT NULL,
    SupplierID INT NOT NULL,

    PRIMARY KEY (ProductID, SupplierID),

    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE,
    FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS STOCK (
    StockID INT AUTO_INCREMENT PRIMARY KEY,
    ProductID INT NOT NULL UNIQUE,
    Quantity INT NOT NULL DEFAULT 0,
    MinStockLevel INT NOT NULL DEFAULT 5,
    HealthStatus ENUM('Healthy','Low','Critical') DEFAULT 'Healthy',
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT check_qty CHECK (Quantity >= 0),
    CONSTRAINT check_min CHECK (MinStockLevel >= 0),

    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE,

    INDEX idx_stock_qty (Quantity)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS STOCK_FLAG (
    FlagID INT AUTO_INCREMENT PRIMARY KEY,
    StockID INT NOT NULL,
    FlaggedByUserID INT NOT NULL,
    Note TEXT,
    FlaggedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (StockID) REFERENCES STOCK(StockID) ON DELETE CASCADE,
    FOREIGN KEY (FlaggedByUserID) REFERENCES USER(UserID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PURCHASE_ORDER (
    POID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    SupplierID INT NOT NULL,
    CreatedByUserID INT NOT NULL,
    OrderDate DATE NOT NULL,
    ExpectedDate DATE,
    Status ENUM('pending','received','cancelled') DEFAULT 'pending',

    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,
    FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID) ON DELETE RESTRICT,
    FOREIGN KEY (CreatedByUserID) REFERENCES USER(UserID) ON DELETE RESTRICT,

    INDEX idx_po_store (StoreID),
    INDEX idx_po_status (Status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PURCHASE_ORDER_ITEM (
    POItemID INT AUTO_INCREMENT PRIMARY KEY,
    POID INT NOT NULL,
    ProductID INT NOT NULL,
    QuantityOrdered INT NOT NULL,
    UnitCost DECIMAL(10,2) NOT NULL,

    CONSTRAINT check_order_qty CHECK (QuantityOrdered > 0),
    CONSTRAINT check_cost CHECK (UnitCost > 0),

    FOREIGN KEY (POID) REFERENCES PURCHASE_ORDER(POID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DELETION_LOG (
    LogID INT AUTO_INCREMENT PRIMARY KEY,
    TableName VARCHAR(100) NOT NULL,
    RecordID INT NOT NULL,
    SnapshotData JSON NOT NULL,
    DeletedByUserID INT NOT NULL,
    StoreID INT NOT NULL,
    DeletedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ExpiresAt TIMESTAMP NOT NULL,
    RestoredAt TIMESTAMP NULL,
    IsRestored TINYINT(1) DEFAULT 0,

    FOREIGN KEY (DeletedByUserID) REFERENCES USER(UserID) ON DELETE RESTRICT,
    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,

    INDEX idx_del_store (StoreID),
    INDEX idx_del_expire (ExpiresAt)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BACKUP_SNAPSHOT (
    BackupID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    TriggeredByUserID INT NOT NULL,
    SnapshotData LONGTEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Note VARCHAR(255),

    FOREIGN KEY (StoreID) REFERENCES STORE(StoreID) ON DELETE RESTRICT,
    FOREIGN KEY (TriggeredByUserID) REFERENCES USER(UserID) ON DELETE RESTRICT
) ENGINE=InnoDB;

ALTER TABLE STORE
ADD CONSTRAINT fk_store_admin
FOREIGN KEY (AdminUserID) REFERENCES USER(UserID)
ON DELETE SET NULL;

DELIMITER //

CREATE TRIGGER trg_stock_status
BEFORE UPDATE ON STOCK
FOR EACH ROW
BEGIN
    IF NEW.Quantity = 0 THEN
        SET NEW.HealthStatus = 'Critical';
    ELSEIF NEW.Quantity <= NEW.MinStockLevel THEN
        SET NEW.HealthStatus = 'Low';
    ELSE
        SET NEW.HealthStatus = 'Healthy';
    END IF;
END //

DELIMITER ;

SET GLOBAL event_scheduler = ON;

DELIMITER //

CREATE EVENT IF NOT EXISTS cleanup_deleted_logs
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP
DO
BEGIN
    UPDATE DELETION_LOG
    SET IsRestored = 2,
        SnapshotData = JSON_OBJECT('expired', TRUE)
    WHERE ExpiresAt < NOW()
      AND IsRestored = 0;
END //

DELIMITER ;

SHOW TABLES;

SELECT 'database ready' AS Status;